baseURL: https://kylesome.github.io
languageCode: en-us
title: Kyle Stewart
theme: PaperMod
enableRobotsTXT: false

params:
  # opengraph meta tags
  description: Kyle Stewart's blog
  keywords: [Blog, Portfolio]
  author: Kyle Stewart

  # search engine indexing
  robotsNoIndex: true

  # layout config
  defaultTheme: auto
  hideFooter: true
  label:
    text: Home

  # about me section
  homeInfoParams:
    Title: "Hi, my name is Kyle \U0001F44B"
    Content: |
      I'm a software developer turned data engineer who is inspired by tough problems.
      I have over 8 years experience in the ever evolving landscape of software development.
      I thrive in a collaborative culture where I can enable others to do their best work.

  # about me links
  socialIcons:
  - name: linkedin
    url: "https://www.linkedin.com/in/kyle-stewart-2956523a"
  - name: github
    url: "https://github.com/kylesome"
  # - name: cv
  #   url: "https://kylesome.github.io/Kyle_Stewart_CV.pdf"


  # blog post config
  cover:
    hidden: true
  DateFormat: "January, 2022"
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
